
(()=>{
window.RS={progress:0,planHover:0};
const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const header=q('.header'),mobile=q('.mobile'),burger=q('.burger'),warp=q('.page-warp');
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
burger?.addEventListener('click',()=>mobile?.classList.toggle('open'));
qa('a[href]').forEach(a=>{const href=a.getAttribute('href');if(!href||href.startsWith('#')||href.startsWith('mailto:')||href.startsWith('tel:')||a.target==='_blank')return;a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;e.preventDefault();mobile?.classList.remove('open');warp?.classList.add('active');setTimeout(()=>location.href=a.href,520)})});
const cur=q('#cursor'),ring=q('#cursor-ring');let x=innerWidth/2,y=innerHeight/2,rx=x,ry=y;addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY;cur&&(cur.style.transform=`translate(${x-3}px,${y-3}px)`)});function cursorFrame(){rx+=(x-rx)*.16;ry+=(y-ry)*.16;ring&&(ring.style.transform=`translate(${rx-17}px,${ry-17}px)`);requestAnimationFrame(cursorFrame)}cursorFrame();qa('a,button,.glass,.package-tab').forEach(el=>{el.addEventListener('pointerenter',()=>document.body.classList.add('cursor-active'));el.addEventListener('pointerleave',()=>document.body.classList.remove('cursor-active'))});
qa('.btn').forEach(b=>{b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect();const dx=(e.clientX-r.left-r.width/2)*.14,dy=(e.clientY-r.top-r.height/2)*.14;b.style.transform=`translate(${dx}px,${dy}px)`});b.addEventListener('pointerleave',()=>b.style.transform='')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.16});qa('.reveal').forEach(el=>io.observe(el));
const cine=q('.cinematic'),dots=qa('.scroll-meter i'),chapters=qa('.chapter');function updateProgress(){if(cine){const top=cine.offsetTop;const max=Math.max(1,cine.offsetHeight-innerHeight);window.RS.progress=Math.max(0,Math.min(1,(scrollY-top)/max));const idx=Math.min(chapters.length-1,Math.floor(window.RS.progress*chapters.length+.08));dots.forEach((d,i)=>d.classList.toggle('active',i===idx));}else window.RS.progress=Math.min(1,scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight));}addEventListener('scroll',updateProgress,{passive:true});updateProgress();
const toastData=[
['GW','Growth Package','Purchased in Austin, TX'],['100','100/100 SEO Website','Booked in Chicago, IL'],['PL','Plumbing SEO Package','Started in Tampa, FL'],['SC','Scale Package','Started in New York, NY'],['ST','Starter Package','Purchased in Phoenix, AZ'],['SEO','Local SEO Roadmap','Requested in Dallas, TX'],['EM','Empire Strategy Call','Booked in Miami, FL'],['WEB','Website Rebuild','Started in Los Angeles, CA']];
const stack=q('.toast-stack');let ti=0;function spawnToast(){if(!stack)return;const item=toastData[Math.floor(Math.random()*toastData.length)];const el=document.createElement('div');el.className='toast';el.innerHTML=`<div class="toast-icon">${item[0]}</div><div><strong>${item[1]}</strong><span>${item[2]}</span></div><time>${Math.floor(Math.random()*11)+1}m</time>`;stack.append(el);while(stack.children.length>3)stack.firstElementChild.remove();setTimeout(()=>{el.classList.add('out');setTimeout(()=>el.remove(),500)},5200);setTimeout(spawnToast,4200+Math.random()*4800)}setTimeout(spawnToast,1100);
qa('[data-count]').forEach(el=>{let done=false;const obs=new IntersectionObserver(es=>{if(es[0].isIntersecting&&!done){done=true;const end=parseFloat(el.dataset.count),suffix=el.dataset.suffix||'';let st=performance.now();function a(n){let p=Math.min(1,(n-st)/1300);el.textContent=(end%1? (end*p).toFixed(1):Math.round(end*p).toLocaleString())+suffix;if(p<1)requestAnimationFrame(a)}requestAnimationFrame(a)}});obs.observe(el)});
const plans={starter:{name:'Starter',price:'$500',unit:'/mo',copy:'Consistent visibility for a business that needs to stop looking inactive and start building a repeatable digital presence.',features:['8 AI-tested short videos every month','Instagram and TikTok management','Caption and hashtag systems','Google Business Profile polish','Monthly performance snapshot'],cta:'Select Starter'},growth:{name:'Growth',price:'$1,000',unit:'/mo',copy:'A complete content and lead system designed to turn attention into calls, forms, bookings and measurable pipeline.',features:['16 premium videos and static creatives','Instagram, TikTok and Facebook','Up to $500 in ad management; ad spend separate','Lead magnet and conversion funnel','Bi-weekly strategy calls','Full content calendar'],cta:'Select Growth'},scale:{name:'Scale',price:'$2,000',unit:'/mo',copy:'Full-stack creative, paid traffic and conversion infrastructure for a business ready to win a competitive market.',features:['30+ high-converting creatives','Meta and TikTok ad management','Up to $2,000 ad-spend management','Landing pages and lead systems','Weekly performance reviews','Competitor creative intelligence'],cta:'Select Scale'},empire:{name:'Empire',price:'$5,000',unit:'/mo',copy:'We operate as your external growth department with strategy, creative, media, SEO, funnels and reporting working as one system.',features:['High-volume creative production','Multi-platform campaign orchestration','Dedicated strategist and creative lead','Custom funnels and CRM architecture','Full SEO and authority program','Direct priority communication'],cta:'Apply for Empire'},website:{name:'100/100 Website',price:'$1,500',unit:'one-time',copy:'A conversion-focused, technically optimized website built to explain your offer clearly, load fast and give search engines the right signals.',features:['Custom responsive design','Technical SEO and schema','Core Web Vitals optimization','Analytics and conversion tracking','Service-page architecture','30-day launch support'],cta:'Request Build'}};
const tabs=qa('.package-tab'),display=q('.package-display');function renderPlan(k){const p=plans[k];if(!p||!display)return;tabs.forEach(t=>t.classList.toggle('active',t.dataset.plan===k));display.innerHTML=`<div class="package-head"><div><div class="eyebrow">Selected launch system</div><h2>${p.name}</h2></div><div class="package-price">${p.price}<small>${p.unit}</small></div></div><p class="package-copy">${p.copy}</p><ul class="feature-list">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><a class="btn" href="contact.html?plan=${k}">${p.cta} →</a>`;window.RS.planHover=Object.keys(plans).indexOf(k)/4;}tabs.forEach(t=>t.addEventListener('click',()=>renderPlan(t.dataset.plan)));if(tabs.length)renderPlan(tabs.find(t=>t.classList.contains('active'))?.dataset.plan||tabs[0].dataset.plan);
const track=q('.review-track');if(track){let down=false,startX=0,startLeft=0;track.addEventListener('pointerdown',e=>{down=true;startX=e.clientX;startLeft=track.scrollLeft;track.setPointerCapture(e.pointerId)});track.addEventListener('pointermove',e=>{if(down)track.scrollLeft=startLeft-(e.clientX-startX)*1.3});track.addEventListener('pointerup',()=>down=false);track.addEventListener('pointercancel',()=>down=false)}
const scan=q('#scan-form'),term=q('#terminal');scan?.addEventListener('submit',e=>{e.preventDefault();const url=q('[name=url]',scan)?.value||'your website';const lines=[`> connecting to ${url}`,'> checking crawl paths...','> reading metadata and service clarity...','> testing mobile performance...','> mapping local search signals...','> checking schema, internal links and authority...','> scan complete','', 'Visibility score: 68 / 100','Primary issue: Google needs clearer service and location signals.','Recommended next move: technical cleanup + service architecture + authority content.'];term.innerHTML='';let i=0;const run=()=>{if(i<lines.length){const d=document.createElement('div');d.textContent=lines[i++];if(i<7)d.className='dim';else if(i>8)d.className='warn';term.append(d);term.scrollTop=term.scrollHeight;setTimeout(run,180+Math.random()*160)}};run()});
const form=q('#contact-form');form?.addEventListener('submit',e=>{e.preventDefault();const name=q('[name=name]',form).value.trim();const email=q('[name=email]',form).value.trim();const plan=q('[name=plan]',form).value;const msg=q('[name=message]',form).value.trim();const subject=encodeURIComponent(`RS Marketing inquiry — ${plan||'Growth strategy'}`);const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\nInterested in: ${plan}\n\n${msg}`);location.href=`mailto:hello.rarescore@gmail.com?subject=${subject}&body=${body}`});
})();
