(()=>{if(!window.THREE)return;const c=document.querySelector('#space');if(!c)return;const r=new THREE.WebGLRenderer({canvas:c,antialias:true,alpha:false});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(innerWidth,innerHeight);r.outputEncoding=THREE.sRGBEncoding;const s=new THREE.Scene();s.fog=new THREE.FogExp2(0x06101e,.012);const cam=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,900);cam.position.set(0,1.5,18);const hemi=new THREE.HemisphereLight(0xaedfff,0x05070a,1.7);s.add(hemi);const sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(-10,14,10);s.add(sun);
// stars with depth
const n=5000,p=new Float32Array(n*3),col=new Float32Array(n*3);for(let i=0;i<n;i++){const z=-Math.random()*650+40;p[i*3]=(Math.random()-.5)*420;p[i*3+1]=(Math.random()-.5)*240;p[i*3+2]=z;const b=.65+Math.random()*.35;col.set([b,b*.95,1],i*3)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));const stars=new THREE.Points(g,new THREE.PointsMaterial({size:.55,vertexColors:true,transparent:true,opacity:.9,sizeAttenuation:true}));s.add(stars);
// earth atmosphere
const earth=new THREE.Mesh(new THREE.SphereGeometry(13,64,64),new THREE.MeshStandardMaterial({color:0x16558e,roughness:.75,metalness:.05,emissive:0x052541,emissiveIntensity:.35}));earth.position.set(0,-16,-14);s.add(earth);const atm=new THREE.Mesh(new THREE.SphereGeometry(13.35,64,64),new THREE.MeshBasicMaterial({color:0x6fdcff,transparent:true,opacity:.12,side:THREE.BackSide}));atm.position.copy(earth.position);s.add(atm);
// B2-like flying wing shape
const shape=new THREE.Shape();shape.moveTo(0,2.2);shape.lineTo(9,-1.4);shape.lineTo(4.2,-.5);shape.lineTo(1.8,-2.2);shape.lineTo(0,-1.1);shape.lineTo(-1.8,-2.2);shape.lineTo(-4.2,-.5);shape.lineTo(-9,-1.4);shape.closePath();const bomber=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.35,bevelEnabled:true,bevelSize:.12,bevelThickness:.12,bevelSegments:3}),new THREE.MeshStandardMaterial({color:0x1a232d,metalness:.78,roughness:.3}));bomber.scale.set(.38,.38,.38);bomber.rotation.x=-Math.PI/2.8;bomber.position.set(0,-2.2,4);s.add(bomber);const engineGlow=new THREE.PointLight(0x73e8ff,4,18);engineGlow.position.set(0,-3,4.5);s.add(engineGlow);
// planet and black hole
const planet=new THREE.Mesh(new THREE.SphereGeometry(5.2,64,64),new THREE.MeshStandardMaterial({color:0xb27648,roughness:.8,metalness:.05,emissive:0x2c130a,emissiveIntensity:.25}));planet.position.set(-20,6,-95);s.add(planet);const hole=new THREE.Mesh(new THREE.SphereGeometry(3.4,64,64),new THREE.MeshBasicMaterial({color:0x000000}));hole.position.set(19,2,-170);s.add(hole);for(let i=0;i<4;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(5.5+i*.7,.32+i*.08,24,180),new THREE.MeshBasicMaterial({color:i%2?0x70e8ff:0xffb45d,transparent:true,opacity:.5-i*.07}));ring.position.copy(hole.position);ring.rotation.x=1.16;ring.rotation.z=i*.23;s.add(ring);ring.userData.spin=.0015+i*.0007}
let mx=0,my=0,sy=0;addEventListener('mousemove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5});addEventListener('scroll',()=>sy=scrollY,{passive:true});function tick(t){requestAnimationFrame(tick);const progress=Math.min(sy/(document.body.scrollHeight-innerHeight||1),1);cam.position.z=18-progress*145;cam.position.x+=(mx*3-cam.position.x)*.025;cam.position.y+=(1.5-my*2-cam.position.y)*.025;bomber.position.z=4-progress*75;bomber.position.y=-2.2+progress*14;bomber.rotation.z=Math.sin(t*.0006)*.08;bomber.rotation.y=progress*.42;earth.rotation.y=t*.00004;stars.position.z=(progress*50)%100;s.children.forEach(o=>{if(o.userData.spin)o.rotation.z+=o.userData.spin});r.render(s,cam)}tick(0);addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)})})();