import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import Lenis from 'lenis'
import Intro from './components/Intro'
import Header from './components/Header'
import { plans, services } from './data/content'
const Experience=lazy(()=>import('./experience/Experience'))
gsap.registerPlugin(ScrollTrigger)
const countFor=(key)=>70+Math.abs([...key].reduce((a,c)=>a*31+c.charCodeAt(0),7))%181
export default function App(){
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches
 const [loaded,setLoaded]=useState(reduced);const progress=useRef(0);const [activeService,setActiveService]=useState('website')
 useEffect(()=>{if(reduced)return;const lenis=new Lenis({duration:1.05,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);const tick=t=>lenis.raf(t*1000);gsap.ticker.add(tick);gsap.ticker.lagSmoothing(0);const st=ScrollTrigger.create({trigger:'#site',start:'top top',end:'bottom bottom',onUpdate:self=>progress.current=self.progress});const ctx=gsap.context(()=>{$$('.reveal').forEach(el=>gsap.from(el,{y:55,opacity:0,duration:1,ease:'power4.out',scrollTrigger:{trigger:el,start:'top 80%'}}))});return()=>{gsap.ticker.remove(tick);lenis.destroy();st.kill();ctx.revert()}},[reduced])
 const s=services[activeService]
 return <><a className="skip-link" href="#site" onClick={()=>setLoaded(true)}>Skip intro</a>{!loaded&&<Intro reducedMotion={reduced} onComplete={()=>setLoaded(true)}/>}<Header/><Suspense fallback={null}><Experience progressRef={progress} reducedMotion={reduced}/></Suspense><main id="site">
 <section className="hero chapter" id="home"><div className="hero-content reveal"><p className="eyebrow"><i/> RS Marketing · Digital growth systems</p><h1 className="display-heading"><span>Your next customer</span><span className="accent">just found someone else.</span></h1><p className="hero-lede">We build the website, SEO, advertising, content, and conversion systems that make sure it does not happen again.</p><div className="button-row"><a className="button" href="#contact">Take back the lead ↗</a><a className="text-link" href="#system">Explore the system →</a></div></div><img className="react-hero-car" src="/assets/rs-formula-car.png" alt="RS Marketing Formula-style car"/></section>
 <section className="chapter" id="system"><div className="section-intro reveal"><p className="eyebrow"><i/>Three ways to start</p><h2>Choose the problem<br/>we solve first.</h2></div><div className="garage-grid">{['Fix visibility now','Build the full engine','Own the market'].map((x,i)=><article className={`garage reveal ${i===1?'garage-featured':''}`} key={x}><div className="garage-number">0{i+1}</div><h3>{x}</h3><p>{['Strengthen rankings, Google visibility, and conversion paths.','Connect website, SEO, advertising, content, and tracking.','Build a complete outsourced marketing and growth department.'][i]}</p><a href="#pricing">Explore the system →</a></article>)}</div></section>
 <section className="chapter services-section" id="services"><div className="section-intro reveal"><p className="eyebrow"><i/>The platform</p><h2>Every system required<br/>to move forward.</h2></div><div className="service-interface reveal"><div className="service-tabs">{Object.keys(services).map(k=><button key={k} aria-selected={activeService===k} onClick={()=>setActiveService(k)}>{k}</button>)}</div><div className="service-stage"><div className="service-copy"><p>{s.index} / {s.kicker}</p><h3>{s.title}</h3><span>{s.copy}</span><ul>{s.items.map(i=><li key={i}>{i}</li>)}</ul></div><div className="service-visual"><div className="telemetry-grid"/><div className="service-orbit"><i/><i/><i/></div></div></div></div></section>
 <section className="chapter pricing-section" id="pricing"><div className="section-intro centered reveal"><p className="eyebrow"><i/>Pricing</p><h2>Choose how fast<br/>you want to grow.</h2></div><div className="pricing-track">{plans.map((p,i)=><article className={`plan reveal ${p.recommended?'plan-recommended':''}`} key={p.name}>{p.recommended&&<div className="recommended-badge">Recommended</div>}<span className="pit-number">0{i+1}</span><h3>{p.name}</h3><div className="price">{p.price}<small>{p.suffix}</small></div><p>{p.copy}</p><ul>{p.items.map(x=><li key={x}>{x}</li>)}</ul><div className="plan-count"><strong>{countFor(p.name)}</strong><span>selected last month</span><em>demo</em></div><a href="#contact">Get started</a></article>)}</div></section>
 <section className="chapter results-section" id="results"><div className="results-head reveal"><div><p className="eyebrow light"><i/>Results telemetry</p><h2>Speed gets attention.<br/>Telemetry wins races.</h2></div></div><div className="results-dashboard reveal">{[['+312%','Organic traffic'],['+189%','Google Business calls'],['+215%','Booked plumbing jobs'],['−37%','Cost per lead']].map(x=><div className="metric" key={x[1]}><span>{x[1]}</span><strong>{x[0]}</strong><small>Sample reporting format</small></div>)}</div></section>
 <section className="chapter seo-section" id="seo-lab"><div className="seo-head reveal"><p className="eyebrow"><i/>SEO Lab</p><h2>Google cannot recommend<br/>what it does not understand.</h2><p>Search systems need a clear identity, relevant service information, geographic context, authority, and technically accessible pages.</p></div></section>
 <section className="chapter contact-section" id="contact"><div className="contact-copy reveal"><p className="eyebrow light"><i/>Start the next lap</p><h2>Your competitor does not<br/>need another head start.</h2><p>Tell us where the business is now and where it needs to go.</p><a className="contact-email" href="mailto:hello.rarescore@gmail.com">hello.rarescore@gmail.com</a></div><form className="contact-form reveal"><label>Name<input required/></label><label>Email<input type="email" required/></label><label>Primary goal<select><option>Free website audit</option><option>SEO strategy</option><option>New website</option><option>Complete growth system</option></select></label><label>Message<textarea rows="5"/></label><button className="button wide">Build my growth plan ↗</button></form></section>
 </main></>
}
function $$(q){return [...document.querySelectorAll(q)]}
